[project]
name = "il1-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.28",
    "openai>=1.97.0",
    "pip>=25.1.1",
    "python-dotenv>=1.1.1",
]
